services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gestor_cursos
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "33061:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+aiomysql://user:password@db/gestor_cursos"
    depends_on:
      db:
        condition: service_healthy  # Espera até o db estar "healthy"
    networks:
      - app_net

  frontend:
    build:
      context: ./interface
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app_net
    depends_on:
      - app


volumes:
  db_data:

networks:
  app_net:
    driver: bridge
