services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+aiomysql://user:password@db/gestor_cursos"  # Use as credenciais adequadas
    depends_on:
      - db

  db:
    image: mysql:latest  # Versão do MySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Senha do root
      MYSQL_DATABASE: gestor_cursos  # Nome do banco de dados
      MYSQL_USER: user  # Nome de usuário
      MYSQL_PASSWORD: password  # Senha do usuário
    ports:
      - "3306:3306"  # Porta padrão do MySQL
    volumes:
      - db_data:/var/lib/mysql  # Persistência de dados

volumes:
  db_data:
